### ISSUE TITLE
Django 1.9 compatibility

### ISSUE THREAD

**Issue by antonagestam** [5monkeys/djedi-cms#18]
Receiving deprecation warnings running Django 1.8

```
djedi-cms/djedi/backends/django/cache/backend.py:18:
RemovedInDjango19Warning: 'get_cache' is deprecated in favor of 'caches'.
  cache = get_cache(cache_name)
```

**Comment by lundberg** [comment]
Related to #22

**Comment by lydell** [comment]
I hacked on it until I could:

1. Login to admin.
2. Add a `{% node %}` in a template.
3. Edit and save that node using djedi’s UI.

This is what I ended up with: https://github.com/5monkeys/djedi-cms/compare/master...lydell:django-1.9

Note: I didn’t bother keeping Django <1.9 compatibility.
